Adds the RWKV model (#218)
* Add rwkv to readme

* Add rwkv result

* Update readme

* Update readme

* Add model

* Data processing

* Ignore unknown args

* Refactor

* Get result progress

* Add get result config

* Use boolean config

* Add data processing configs

* Train progress

* Fix size config

* Train progress

* Separate stats

* Refactor srs_model

* Fix some rnn tests

* Test rnn progress

* srs rnn test

* Add curve test

* rnn progress

* day offset

* Add remaining features rnn

* rnn progress

* Refactor encodings

* Add train config

* Update timeseriessplit description

* Update .gitignore

* Remove comment

* Add helper db config

* Update wandb default

* Update train batch

* Update signature

* Add arg name

* Remove comment

* Update .gitignore

* Update rwkv readme

* Update README.md

* Update config paths

* Fix bold

* Separate rnn code

* Add training info

* Rename rnn

* Delete test folder

* Update .gitignore

* Add rnn config file

* print predictions

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* combine config files

* Remove imports

* Refactor

* Refactor global length config

* Require cuda for training

* Set to false

* Add required packages

* Update README.md

* fix ModuleNotFoundError

* create directory before saving model

RuntimeError: Parent directory pretrain/rwkv/train does not exist.

---------

Co-authored-by: Expertium <83031600+Expertium@users.noreply.github.com>
Co-authored-by: Jarrett Ye <jarrett.ye@outlook.com>